[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600
lib_deps =
    jrowberg/I2Cdevlib-MPU6050@^1.0.0
    links2004/WebSockets@^2.4.0
    madhephaestus/ESP32Servo@^1.1.1
    bblanchon/ArduinoJson@^7.0.0
board_build.filesystem = spiffs
build_flags =
    -DCORE_DEBUG_LEVEL=2

[env:native]
platform = native
build_flags = -std=gnu++17
test_build_src = no
